In [4]:
clause_retrieval_prompt = """
You are a procurement contract analysis assistant.

Your task is to retrieve the most relevant contract clause
based on the given shipment issue.

Contract Clauses:
{contract_clauses}

Shipment Issue:
{shipment_issue}

Instructions:
1. Identify the clause relevant to the shipment issue.
2. Identify the clause category.
3. Return the relevant clause.
4. Explain why the clause is relevant.
5. If no relevant clause is found, return "No Relevant Clause".

Output format:
Clause Category:
Relevant Clause:
Reason:
"""

print("Clause Retrieval Prompt Created Successfully")

Clause Retrieval Prompt Created Successfully

In [5]:
# Sample shipment issue from our shipping dataset

shipment_issue = """
The shipment was delivered 3 days later than the planned delivery date.
The vendor did not notify the buyer about the delay within 24 hours.
"""

print("Shipment Issue:")
print(shipment_issue)

Shipment Issue:

The shipment was delivered 3 days later than the planned delivery date.
The vendor did not notify the buyer about the delay within 24 hours.

In [6]:
# Contract clause knowledge base

contract_clauses = [
    {
        "category": "Delivery",
        "clause": "Supplier must deliver goods within 7 business days."
    },
    {
        "category": "Delay Notification",
        "clause": "Supplier must notify the buyer within 24 hours of any delivery delay."
    },
    {
        "category": "Insurance",
        "clause": "Supplier must maintain valid transportation insurance."
    },
    {
        "category": "Payment",
        "clause": "Payment will be completed within 30 days after successful delivery."
    },
    {
        "category": "Termination",
        "clause": "Either party must provide 30 days notice before termination."
    }
]

print("Total contract clauses:", len(contract_clauses))

for clause in contract_clauses:
    print(f"\nCategory: {clause['category']}")
    print(f"Clause: {clause['clause']}")

Total contract clauses: 5

Category: Delivery
Clause: Supplier must deliver goods within 7 business days.

Category: Delay Notification
Clause: Supplier must notify the buyer within 24 hours of any delivery delay.

Category: Insurance
Clause: Supplier must maintain valid transportation insurance.

Category: Payment
Clause: Payment will be completed within 30 days after successful delivery.

Category: Termination
Clause: Either party must provide 30 days notice before termination.

In [7]:
def retrieve_relevant_clauses(shipment_issue, contract_clauses):
    """
    Retrieve contract clauses relevant to a shipment issue.
    """

    keywords = {
        "delivery": ["delivery", "delivered", "days", "late", "delay"],
        "delay notification": ["delay", "notify", "notification", "24 hours"],
        "insurance": ["insurance", "insured"],
        "payment": ["payment", "paid"],
        "termination": ["termination", "terminate", "notice"]
    }

    issue_text = shipment_issue.lower()

    matched_clauses = []

    for clause in contract_clauses:
        category = clause["category"].lower()
        clause_text = clause["clause"].lower()

        search_words = keywords.get(category, [])

        if any(word in issue_text for word in search_words):
            matched_clauses.append(clause)

    return matched_clauses


# Retrieve relevant clauses
relevant_clauses = retrieve_relevant_clauses(
    shipment_issue,
    contract_clauses
)

print("Relevant Clauses Found:")
print("-" * 50)

for clause in relevant_clauses:
    print("Category:", clause["category"])
    print("Clause:", clause["clause"])
    print()

Relevant Clauses Found:
--------------------------------------------------
Category: Delivery
Clause: Supplier must deliver goods within 7 business days.

Category: Delay Notification
Clause: Supplier must notify the buyer within 24 hours of any delivery delay.

In [8]:
def analyze_compliance(shipment_issue, relevant_clauses):
    """
    Analyze shipment compliance against relevant contract clauses.
    """

    issue_text = shipment_issue.lower()

    results = []

    for clause in relevant_clauses:
        category = clause["category"]
        clause_text = clause["clause"]

        if category == "Delivery":
            if "late" in issue_text or "delay" in issue_text or "3 days later" in issue_text:
                status = "Non-Compliant"
                violation = "Delivery exceeded the contractual delivery period."
                risk = "High"
                recommendation = "Review vendor performance and initiate the delay procedure."
            else:
                status = "Compliant"
                violation = "No delivery violation identified."
                risk = "Low"
                recommendation = "Continue monitoring vendor performance."

        elif category == "Delay Notification":
            if "did not notify" in issue_text or "not notify" in issue_text:
                status = "Non-Compliant"
                violation = "Required delay notification was not provided within 24 hours."
                risk = "High"
                recommendation = "Request an explanation from the vendor and review the contract's delay procedure."
            else:
                status = "Compliant"
                violation = "No notification violation identified."
                risk = "Low"
                recommendation = "Continue monitoring compliance."

        else:
            status = "Needs Review"
            violation = "No automatic rule available for this clause."
            risk = "Medium"
            recommendation = "Perform manual contract review."

        results.append({
            "Category": category,
            "Clause": clause_text,
            "Status": status,
            "Violation": violation,
            "Risk": risk,
            "Recommendation": recommendation
        })

    return results


# Run compliance analysis
compliance_results = analyze_compliance(
    shipment_issue,
    relevant_clauses
)

for result in compliance_results:
    print("Category:", result["Category"])
    print("Status:", result["Status"])
    print("Violation:", result["Violation"])
    print("Risk:", result["Risk"])
    print("Recommendation:", result["Recommendation"])
    print("-" * 60)

Category: Delivery
Status: Non-Compliant
Violation: Delivery exceeded the contractual delivery period.
Risk: High
Recommendation: Review vendor performance and initiate the delay procedure.
------------------------------------------------------------
Category: Delay Notification
Status: Non-Compliant
Violation: Required delay notification was not provided within 24 hours.
Risk: High
Recommendation: Request an explanation from the vendor and review the contract's delay procedure.
------------------------------------------------------------

In [9]:
import pandas as pd

compliance_report = pd.DataFrame(compliance_results)

print("COMPLIANCE ANALYSIS REPORT")
print("=" * 80)

display(compliance_report)

COMPLIANCE ANALYSIS REPORT
================================================================================

,Category,Clause,Status,Violation,Risk,Recommendation
0,Delivery,Supplier must deliver goods within 7 business ...,Non-Compliant,Delivery exceeded the contractual delivery per...,High,Review vendor performance and initiate the del...
1,Delay Notification,Supplier must notify the buyer within 24 hours...,Non-Compliant,Required delay notification was not provided w...,High,Request an explanation from the vendor and rev...

In [10]:
# Determine overall risk

if "High" in compliance_report["Risk"].values:
    overall_risk = "High"
elif "Medium" in compliance_report["Risk"].values:
    overall_risk = "Medium"
else:
    overall_risk = "Low"

print("Overall Compliance Risk:", overall_risk)

Overall Compliance Risk: High

In [11]:
print("=" * 80)
print("FINAL CONTRACT COMPLIANCE SUMMARY")
print("=" * 80)

print("Shipment Issue:")
print(shipment_issue)

print("\nOverall Risk:", overall_risk)

print("\nCompliance Findings:")

for result in compliance_results:
    print(f"\n• {result['Category']}")
    print(f"  Status: {result['Status']}")
    print(f"  Risk: {result['Risk']}")
    print(f"  Violation: {result['Violation']}")
    print(f"  Recommendation: {result['Recommendation']}")

================================================================================
FINAL CONTRACT COMPLIANCE SUMMARY
================================================================================
Shipment Issue:

The shipment was delivered 3 days later than the planned delivery date.
The vendor did not notify the buyer about the delay within 24 hours.


Overall Risk: High

Compliance Findings:

• Delivery
  Status: Non-Compliant
  Risk: High
  Violation: Delivery exceeded the contractual delivery period.
  Recommendation: Review vendor performance and initiate the delay procedure.

• Delay Notification
  Status: Non-Compliant
  Risk: High
  Violation: Required delay notification was not provided within 24 hours.
  Recommendation: Request an explanation from the vendor and review the contract's delay procedure.

In [18]:
import os

files = os.listdir("/content")

print("Files in Colab:")
for file in files:
    print(file)

Files in Colab:
.config
sample_data

In [20]:
from google.colab import files

uploaded = files.upload()

Saving shipping_data.csv to shipping_data.csv

In [21]:
import pandas as pd

filename = list(uploaded.keys())[0]

shipping_df = pd.read_csv(filename)

print("File loaded:", filename)
print("Dataset Shape:", shipping_df.shape)

display(shipping_df.head())

File loaded: shipping_data.csv
Dataset Shape: (500, 12)

,Shipment_ID,Vendor,Origin,Destination,Shipping_Mode,Distance_km,Weather,Traffic,Planned_Delivery_Days,Actual_Delivery_Days,Delay_Days,Delayed
0,SHP0001,Beta Suppliers,Chennai,Mumbai,Rail,964,Clear,Low,2,2,0,0
1,SHP0002,Omega Supplies,Chennai,Coimbatore,Rail,1002,Rain,Low,3,5,2,1
2,SHP0003,Prime Logistics,Mumbai,Chennai,Rail,1781,Clear,Low,3,3,0,0
3,SHP0004,Beta Suppliers,Coimbatore,Pune,Road,1520,Storm,Medium,3,6,3,1
4,SHP0005,Omega Supplies,Coimbatore,Mumbai,Air,2414,Clear,Low,5,5,0,0

In [22]:
def create_shipment_issue(row):
    if row["Delay_Days"] > 0:
        return (
            f"Vendor {row['Vendor']} delivered shipment "
            f"{row['Shipment_ID']} {row['Delay_Days']} days late. "
            f"Planned delivery was {row['Planned_Delivery_Days']} days "
            f"and actual delivery was {row['Actual_Delivery_Days']} days."
        )
    else:
        return (
            f"Vendor {row['Vendor']} delivered shipment "
            f"{row['Shipment_ID']} within the planned delivery period."
        )


shipping_df["Shipment_Issue"] = shipping_df.apply(
    create_shipment_issue,
    axis=1
)

display(
    shipping_df[
        [
            "Shipment_ID",
            "Vendor",
            "Planned_Delivery_Days",
            "Actual_Delivery_Days",
            "Delay_Days",
            "Shipment_Issue"
        ]
    ].head(10)
)

,Shipment_ID,Vendor,Planned_Delivery_Days,Actual_Delivery_Days,Delay_Days,Shipment_Issue
0,SHP0001,Beta Suppliers,2,2,0,Vendor Beta Suppliers delivered shipment SHP00...
1,SHP0002,Omega Supplies,3,5,2,Vendor Omega Supplies delivered shipment SHP00...
2,SHP0003,Prime Logistics,3,3,0,Vendor Prime Logistics delivered shipment SHP0...
3,SHP0004,Beta Suppliers,3,6,3,Vendor Beta Suppliers delivered shipment SHP00...
4,SHP0005,Omega Supplies,5,5,0,Vendor Omega Supplies delivered shipment SHP00...
5,SHP0006,Epsilon Exports,4,4,0,Vendor Epsilon Exports delivered shipment SHP0...
6,SHP0007,Delta Traders,6,7,1,Vendor Delta Traders delivered shipment SHP000...
7,SHP0008,Zeta Manufacturing,2,3,1,Vendor Zeta Manufacturing delivered shipment S...
8,SHP0009,Delta Traders,1,3,2,Vendor Delta Traders delivered shipment SHP000...
9,SHP0010,Omega Supplies,2,2,0,Vendor Omega Supplies delivered shipment SHP00...

In [23]:
def retrieve_clause_for_shipment(shipment_issue):
    matched = retrieve_relevant_clauses(
        shipment_issue,
        contract_clauses
    )

    if len(matched) == 0:
        return "No Relevant Clause"

    return " | ".join(
        [
            f"{c['category']}: {c['clause']}"
            for c in matched
        ]
    )


shipping_df["Relevant_Clause"] = shipping_df["Shipment_Issue"].apply(
    retrieve_clause_for_shipment
)

display(
    shipping_df[
        [
            "Shipment_ID",
            "Vendor",
            "Shipment_Issue",
            "Relevant_Clause"
        ]
    ].head(10)
)

,Shipment_ID,Vendor,Shipment_Issue,Relevant_Clause
0,SHP0001,Beta Suppliers,Vendor Beta Suppliers delivered shipment SHP00...,Delivery: Supplier must deliver goods within 7...
1,SHP0002,Omega Supplies,Vendor Omega Supplies delivered shipment SHP00...,Delivery: Supplier must deliver goods within 7...
2,SHP0003,Prime Logistics,Vendor Prime Logistics delivered shipment SHP0...,Delivery: Supplier must deliver goods within 7...
3,SHP0004,Beta Suppliers,Vendor Beta Suppliers delivered shipment SHP00...,Delivery: Supplier must deliver goods within 7...
4,SHP0005,Omega Supplies,Vendor Omega Supplies delivered shipment SHP00...,Delivery: Supplier must deliver goods within 7...
5,SHP0006,Epsilon Exports,Vendor Epsilon Exports delivered shipment SHP0...,Delivery: Supplier must deliver goods within 7...
6,SHP0007,Delta Traders,Vendor Delta Traders delivered shipment SHP000...,Delivery: Supplier must deliver goods within 7...
7,SHP0008,Zeta Manufacturing,Vendor Zeta Manufacturing delivered shipment S...,Delivery: Supplier must deliver goods within 7...
8,SHP0009,Delta Traders,Vendor Delta Traders delivered shipment SHP000...,Delivery: Supplier must deliver goods within 7...
9,SHP0010,Omega Supplies,Vendor Omega Supplies delivered shipment SHP00...,Delivery: Supplier must deliver goods within 7...

In [24]:
def analyze_shipment_compliance(row):

    planned = row["Planned_Delivery_Days"]
    actual = row["Actual_Delivery_Days"]
    delay = row["Delay_Days"]

    # Delivery compliance
    if delay > 0:
        status = "Non-Compliant"
        risk = "High"

        violation = (
            f"Shipment delayed by {delay} day(s). "
            f"Planned delivery: {planned} days; "
            f"Actual delivery: {actual} days."
        )

        recommendation = (
            "Review vendor performance and check "
            "the contract delay requirements."
        )

    else:
        status = "Compliant"
        risk = "Low"

        violation = "No delivery delay detected."

        recommendation = (
            "Continue monitoring vendor performance."
        )

    return pd.Series({
        "Compliance_Status": status,
        "Compliance_Risk": risk,
        "Compliance_Violation": violation,
        "Recommendation": recommendation
    })


shipping_df[
    [
        "Compliance_Status",
        "Compliance_Risk",
        "Compliance_Violation",
        "Recommendation"
    ]
] = shipping_df.apply(
    analyze_shipment_compliance,
    axis=1
)

print("Compliance analysis completed for all shipments.")

Compliance analysis completed for all shipments.

In [25]:
compliance_columns = [
    "Shipment_ID",
    "Vendor",
    "Delay_Days",
    "Delayed",
    "Relevant_Clause",
    "Compliance_Status",
    "Compliance_Risk",
    "Compliance_Violation",
    "Recommendation"
]

display(
    shipping_df[compliance_columns].head(20)
)

,Shipment_ID,Vendor,Delay_Days,Delayed,Relevant_Clause,Compliance_Status,Compliance_Risk,Compliance_Violation,Recommendation
0,SHP0001,Beta Suppliers,0,0,Delivery: Supplier must deliver goods within 7...,Compliant,Low,No delivery delay detected.,Continue monitoring vendor performance.
1,SHP0002,Omega Supplies,2,1,Delivery: Supplier must deliver goods within 7...,Non-Compliant,High,Shipment delayed by 2 day(s). Planned delivery...,Review vendor performance and check the contra...
2,SHP0003,Prime Logistics,0,0,Delivery: Supplier must deliver goods within 7...,Compliant,Low,No delivery delay detected.,Continue monitoring vendor performance.
3,SHP0004,Beta Suppliers,3,1,Delivery: Supplier must deliver goods within 7...,Non-Compliant,High,Shipment delayed by 3 day(s). Planned delivery...,Review vendor performance and check the contra...
4,SHP0005,Omega Supplies,0,0,Delivery: Supplier must deliver goods within 7...,Compliant,Low,No delivery delay detected.,Continue monitoring vendor performance.
5,SHP0006,Epsilon Exports,0,0,Delivery: Supplier must deliver goods within 7...,Compliant,Low,No delivery delay detected.,Continue monitoring vendor performance.
6,SHP0007,Delta Traders,1,1,Delivery: Supplier must deliver goods within 7...,Non-Compliant,High,Shipment delayed by 1 day(s). Planned delivery...,Review vendor performance and check the contra...
7,SHP0008,Zeta Manufacturing,1,1,Delivery: Supplier must deliver goods within 7...,Non-Compliant,High,Shipment delayed by 1 day(s). Planned delivery...,Review vendor performance and check the contra...
8,SHP0009,Delta Traders,2,1,Delivery: Supplier must deliver goods within 7...,Non-Compliant,High,Shipment delayed by 2 day(s). Planned delivery...,Review vendor performance and check the contra...
9,SHP0010,Omega Supplies,0,0,Delivery: Supplier must deliver goods within 7...,Compliant,Low,No delivery delay detected.,Continue monitoring vendor performance.
10,SHP0011,Gamma Industries,2,1,Delivery: Supplier must deliver goods within 7...,Non-Compliant,High,Shipment delayed by 2 day(s). Planned delivery...,Review vendor performance and check the contra...
11,SHP0012,Zeta Manufacturing,4,1,Delivery: Supplier must deliver goods within 7...,Non-Compliant,High,Shipment delayed by 4 day(s). Planned delivery...,Review vendor performance and check the contra...
12,SHP0013,Beta Suppliers,2,1,Delivery: Supplier must deliver goods within 7...,Non-Compliant,High,Shipment delayed by 2 day(s). Planned delivery...,Review vendor performance and check the contra...
13,SHP0014,Alpha Logistics,1,1,Delivery: Supplier must deliver goods within 7...,Non-Compliant,High,Shipment delayed by 1 day(s). Planned delivery...,Review vendor performance and check the contra...
14,SHP0015,Prime Logistics,4,1,Delivery: Supplier must deliver goods within 7...,Non-Compliant,High,Shipment delayed by 4 day(s). Planned delivery...,Review vendor performance and check the contra...
15,SHP0016,Delta Traders,2,1,Delivery: Supplier must deliver goods within 7...,Non-Compliant,High,Shipment delayed by 2 day(s). Planned delivery...,Review vendor performance and check the contra...
16,SHP0017,Alpha Logistics,2,1,Delivery: Supplier must deliver goods within 7...,Non-Compliant,High,Shipment delayed by 2 day(s). Planned delivery...,Review vendor performance and check the contra...
17,SHP0018,Epsilon Exports,2,1,Delivery: Supplier must deliver goods within 7...,Non-Compliant,High,Shipment delayed by 2 day(s). Planned delivery...,Review vendor performance and check the contra...
18,SHP0019,Beta Suppliers,3,1,Delivery: Supplier must deliver goods within 7...,Non-Compliant,High,Shipment delayed by 3 day(s). Planned delivery...,Review vendor performance and check the contra...
19,SHP0020,Alpha Logistics,1,1,Delivery: Supplier must deliver goods within 7...,Non-Compliant,High,Shipment delayed by 1 day(s). Planned delivery...,Review vendor performance and check the contra...

In [26]:
print("COMPLIANCE SUMMARY")
print("=" * 50)

print("\nCompliance Status:")
print(shipping_df["Compliance_Status"].value_counts())

print("\nRisk Distribution:")
print(shipping_df["Compliance_Risk"].value_counts())

COMPLIANCE SUMMARY
==================================================

Compliance Status:
Compliance_Status
Non-Compliant    405
Compliant         95
Name: count, dtype: int64

Risk Distribution:
Compliance_Risk
High    405
Low      95
Name: count, dtype: int64

In [27]:
vendor_evaluation = (
    shipping_df
    .groupby("Vendor")
    .agg(
        Total_Shipments=("Shipment_ID", "count"),
        Delayed_Shipments=("Delay_Days", lambda x: (x > 0).sum()),
        Average_Delay_Days=("Delay_Days", "mean"),
        Compliant_Shipments=(
            "Compliance_Status",
            lambda x: (x == "Compliant").sum()
        ),
        Non_Compliant_Shipments=(
            "Compliance_Status",
            lambda x: (x == "Non-Compliant").sum()
        ),
        High_Risk_Shipments=(
            "Compliance_Risk",
            lambda x: (x == "High").sum()
        )
    )
    .reset_index()
)

vendor_evaluation["Delay_Rate_%"] = (
    vendor_evaluation["Delayed_Shipments"]
    / vendor_evaluation["Total_Shipments"]
    * 100
).round(2)

vendor_evaluation["Compliance_Rate_%"] = (
    vendor_evaluation["Compliant_Shipments"]
    / vendor_evaluation["Total_Shipments"]
    * 100
).round(2)

vendor_evaluation["Average_Delay_Days"] = (
    vendor_evaluation["Average_Delay_Days"]
    .round(2)
)

display(vendor_evaluation)

,Vendor,Total_Shipments,Delayed_Shipments,Average_Delay_Days,Compliant_Shipments,Non_Compliant_Shipments,High_Risk_Shipments,Delay_Rate_%,Compliance_Rate_%
0,Alpha Logistics,48,41,2.10,7,41,41,85.42,14.58
1,Beta Suppliers,65,55,1.98,10,55,55,84.62,15.38
2,Delta Traders,62,52,1.84,10,52,52,83.87,16.13
3,Epsilon Exports,62,52,2.47,10,52,52,83.87,16.13
4,Gamma Industries,79,68,2.00,11,68,68,86.08,13.92
5,Omega Supplies,60,44,1.72,16,44,44,73.33,26.67
6,Prime Logistics,69,50,2.10,19,50,50,72.46,27.54
7,Zeta Manufacturing,55,43,1.93,12,43,43,78.18,21.82

In [28]:
def assign_vendor_risk(row):

    if row["Delay_Rate_%"] >= 50 or row["High_Risk_Shipments"] >= 5:
        return "High"

    elif row["Delay_Rate_%"] >= 25 or row["High_Risk_Shipments"] >= 2:
        return "Medium"

    else:
        return "Low"


vendor_evaluation["Overall_Risk"] = vendor_evaluation.apply(
    assign_vendor_risk,
    axis=1
)

display(vendor_evaluation)

,Vendor,Total_Shipments,Delayed_Shipments,Average_Delay_Days,Compliant_Shipments,Non_Compliant_Shipments,High_Risk_Shipments,Delay_Rate_%,Compliance_Rate_%,Overall_Risk
0,Alpha Logistics,48,41,2.10,7,41,41,85.42,14.58,High
1,Beta Suppliers,65,55,1.98,10,55,55,84.62,15.38,High
2,Delta Traders,62,52,1.84,10,52,52,83.87,16.13,High
3,Epsilon Exports,62,52,2.47,10,52,52,83.87,16.13,High
4,Gamma Industries,79,68,2.00,11,68,68,86.08,13.92,High
5,Omega Supplies,60,44,1.72,16,44,44,73.33,26.67,High
6,Prime Logistics,69,50,2.10,19,50,50,72.46,27.54,High
7,Zeta Manufacturing,55,43,1.93,12,43,43,78.18,21.82,High

In [29]:
print("VENDOR RISK SUMMARY")
print("=" * 50)

print(
    vendor_evaluation["Overall_Risk"].value_counts()
)

VENDOR RISK SUMMARY
==================================================
Overall_Risk
High    8
Name: count, dtype: int64

In [30]:
vendor_report = vendor_evaluation[
    [
        "Vendor",
        "Total_Shipments",
        "Delayed_Shipments",
        "Delay_Rate_%",
        "Average_Delay_Days",
        "Compliant_Shipments",
        "Non_Compliant_Shipments",
        "High_Risk_Shipments",
        "Compliance_Rate_%",
        "Overall_Risk"
    ]
].copy()

display(vendor_report)

,Vendor,Total_Shipments,Delayed_Shipments,Delay_Rate_%,Average_Delay_Days,Compliant_Shipments,Non_Compliant_Shipments,High_Risk_Shipments,Compliance_Rate_%,Overall_Risk
0,Alpha Logistics,48,41,85.42,2.10,7,41,41,14.58,High
1,Beta Suppliers,65,55,84.62,1.98,10,55,55,15.38,High
2,Delta Traders,62,52,83.87,1.84,10,52,52,16.13,High
3,Epsilon Exports,62,52,83.87,2.47,10,52,52,16.13,High
4,Gamma Industries,79,68,86.08,2.00,11,68,68,13.92,High
5,Omega Supplies,60,44,73.33,1.72,16,44,44,26.67,High
6,Prime Logistics,69,50,72.46,2.10,19,50,50,27.54,High
7,Zeta Manufacturing,55,43,78.18,1.93,12,43,43,21.82,High

In [31]:
vendor_report["Vendor_Score"] = (
    100
    - (vendor_report["Delay_Rate_%"] * 0.6)
    - (vendor_report["High_Risk_Shipments"] /
       vendor_report["Total_Shipments"] * 100 * 0.4)
).clip(0, 100).round(2)

display(vendor_report)

,Vendor,Total_Shipments,Delayed_Shipments,Delay_Rate_%,Average_Delay_Days,Compliant_Shipments,Non_Compliant_Shipments,High_Risk_Shipments,Compliance_Rate_%,Overall_Risk,Vendor_Score
0,Alpha Logistics,48,41,85.42,2.10,7,41,41,14.58,High,14.58
1,Beta Suppliers,65,55,84.62,1.98,10,55,55,15.38,High,15.38
2,Delta Traders,62,52,83.87,1.84,10,52,52,16.13,High,16.13
3,Epsilon Exports,62,52,83.87,2.47,10,52,52,16.13,High,16.13
4,Gamma Industries,79,68,86.08,2.00,11,68,68,13.92,High,13.92
5,Omega Supplies,60,44,73.33,1.72,16,44,44,26.67,High,26.67
6,Prime Logistics,69,50,72.46,2.10,19,50,50,27.54,High,27.54
7,Zeta Manufacturing,55,43,78.18,1.93,12,43,43,21.82,High,21.82

In [32]:
def vendor_recommendation(row):

    if row["Overall_Risk"] == "High":
        return (
            "Detailed vendor review required. "
            "Monitor delivery delays and contract compliance."
        )

    elif row["Overall_Risk"] == "Medium":
        return (
            "Monitor vendor performance and "
            "review recurring delays."
        )

    else:
        return (
            "Continue routine monitoring of "
            "delivery and compliance performance."
        )


vendor_report["Recommendation"] = vendor_report.apply(
    vendor_recommendation,
    axis=1
)

display(vendor_report)

,Vendor,Total_Shipments,Delayed_Shipments,Delay_Rate_%,Average_Delay_Days,Compliant_Shipments,Non_Compliant_Shipments,High_Risk_Shipments,Compliance_Rate_%,Overall_Risk,Vendor_Score,Recommendation
0,Alpha Logistics,48,41,85.42,2.10,7,41,41,14.58,High,14.58,Detailed vendor review required. Monitor deliv...
1,Beta Suppliers,65,55,84.62,1.98,10,55,55,15.38,High,15.38,Detailed vendor review required. Monitor deliv...
2,Delta Traders,62,52,83.87,1.84,10,52,52,16.13,High,16.13,Detailed vendor review required. Monitor deliv...
3,Epsilon Exports,62,52,83.87,2.47,10,52,52,16.13,High,16.13,Detailed vendor review required. Monitor deliv...
4,Gamma Industries,79,68,86.08,2.00,11,68,68,13.92,High,13.92,Detailed vendor review required. Monitor deliv...
5,Omega Supplies,60,44,73.33,1.72,16,44,44,26.67,High,26.67,Detailed vendor review required. Monitor deliv...
6,Prime Logistics,69,50,72.46,2.10,19,50,50,27.54,High,27.54,Detailed vendor review required. Monitor deliv...
7,Zeta Manufacturing,55,43,78.18,1.93,12,43,43,21.82,High,21.82,Detailed vendor review required. Monitor deliv...

In [33]:
print("=" * 80)
print("AUTOMATED VENDOR EVALUATION AGENT")
print("=" * 80)

for _, row in vendor_report.iterrows():

    print(f"\nVendor: {row['Vendor']}")
    print(f"Total Shipments: {row['Total_Shipments']}")
    print(f"Delayed Shipments: {row['Delayed_Shipments']}")
    print(f"Delay Rate: {row['Delay_Rate_%']}%")
    print(f"Compliance Rate: {row['Compliance_Rate_%']}%")
    print(f"High-Risk Shipments: {row['High_Risk_Shipments']}")
    print(f"Vendor Score: {row['Vendor_Score']}/100")
    print(f"Overall Risk: {row['Overall_Risk']}")
    print(f"Recommendation: {row['Recommendation']}")
    print("-" * 80)

================================================================================
AUTOMATED VENDOR EVALUATION AGENT
================================================================================

Vendor: Alpha Logistics
Total Shipments: 48
Delayed Shipments: 41
Delay Rate: 85.42%
Compliance Rate: 14.58%
High-Risk Shipments: 41
Vendor Score: 14.58/100
Overall Risk: High
Recommendation: Detailed vendor review required. Monitor delivery delays and contract compliance.
--------------------------------------------------------------------------------

Vendor: Beta Suppliers
Total Shipments: 65
Delayed Shipments: 55
Delay Rate: 84.62%
Compliance Rate: 15.38%
High-Risk Shipments: 55
Vendor Score: 15.38/100
Overall Risk: High
Recommendation: Detailed vendor review required. Monitor delivery delays and contract compliance.
--------------------------------------------------------------------------------

Vendor: Delta Traders
Total Shipments: 62
Delayed Shipments: 52
Delay Rate: 83.87%
Compliance Rate: 16.13%
High-Risk Shipments: 52
Vendor Score: 16.13/100
Overall Risk: High
Recommendation: Detailed vendor review required. Monitor delivery delays and contract compliance.
--------------------------------------------------------------------------------

Vendor: Epsilon Exports
Total Shipments: 62
Delayed Shipments: 52
Delay Rate: 83.87%
Compliance Rate: 16.13%
High-Risk Shipments: 52
Vendor Score: 16.13/100
Overall Risk: High
Recommendation: Detailed vendor review required. Monitor delivery delays and contract compliance.
--------------------------------------------------------------------------------

Vendor: Gamma Industries
Total Shipments: 79
Delayed Shipments: 68
Delay Rate: 86.08%
Compliance Rate: 13.92%
High-Risk Shipments: 68
Vendor Score: 13.92/100
Overall Risk: High
Recommendation: Detailed vendor review required. Monitor delivery delays and contract compliance.
--------------------------------------------------------------------------------

Vendor: Omega Supplies
Total Shipments: 60
Delayed Shipments: 44
Delay Rate: 73.33%
Compliance Rate: 26.67%
High-Risk Shipments: 44
Vendor Score: 26.67/100
Overall Risk: High
Recommendation: Detailed vendor review required. Monitor delivery delays and contract compliance.
--------------------------------------------------------------------------------

Vendor: Prime Logistics
Total Shipments: 69
Delayed Shipments: 50
Delay Rate: 72.46%
Compliance Rate: 27.54%
High-Risk Shipments: 50
Vendor Score: 27.54/100
Overall Risk: High
Recommendation: Detailed vendor review required. Monitor delivery delays and contract compliance.
--------------------------------------------------------------------------------

Vendor: Zeta Manufacturing
Total Shipments: 55
Delayed Shipments: 43
Delay Rate: 78.18%
Compliance Rate: 21.82%
High-Risk Shipments: 43
Vendor Score: 21.82/100
Overall Risk: High
Recommendation: Detailed vendor review required. Monitor delivery delays and contract compliance.
--------------------------------------------------------------------------------

In [34]:
shipping_df.to_csv(
    "shipment_compliance_report.csv",
    index=False
)

print("Saved: shipment_compliance_report.csv")

Saved: shipment_compliance_report.csv

In [35]:
vendor_report.to_csv(
    "vendor_evaluation_report.csv",
    index=False
)

print("Saved: vendor_evaluation_report.csv")

Saved: vendor_evaluation_report.csv

In [36]:
from google.colab import files

files.download("shipment_compliance_report.csv")
files.download("vendor_evaluation_report.csv")

In [37]:
print("=" * 70)
print("DABA DAY 2 - FINAL PROJECT SUMMARY")
print("=" * 70)

print(f"Total Shipments: {len(shipping_df)}")

print(
    f"Delayed Shipments: "
    f"{(shipping_df['Delay_Days'] > 0).sum()}"
)

print(
    f"Compliant Shipments: "
    f"{(shipping_df['Compliance_Status'] == 'Compliant').sum()}"
)

print(
    f"Non-Compliant Shipments: "
    f"{(shipping_df['Compliance_Status'] == 'Non-Compliant').sum()}"
)

print(
    f"High-Risk Shipments: "
    f"{(shipping_df['Compliance_Risk'] == 'High').sum()}"
)

print(f"Total Vendors: {vendor_report['Vendor'].nunique()}")

print("\nVendor Risk Distribution:")
print(vendor_report["Overall_Risk"].value_counts())

print("\nProject workflow completed successfully.")

======================================================================
DABA DAY 2 - FINAL PROJECT SUMMARY
======================================================================
Total Shipments: 500
Delayed Shipments: 405
Compliant Shipments: 95
Non-Compliant Shipments: 405
High-Risk Shipments: 405
Total Vendors: 8

Vendor Risk Distribution:
Overall_Risk
High    8
Name: count, dtype: int64

Project workflow completed successfully.